# Generated by Django 4.2.1 on 2023-05-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('number_of_copies', models.IntegerField()),
            ],
        ),
    ]
